name: publish release
on:
  push:
    branches: [ master ]
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew app:assembleRelease
      - name: Upload apk to artifact
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: lottery_app
          path: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: app/build/outputs/apk/release/*.apk
          tag: ${{ github.run_id }}
          release_name: ${{ github.run_id }}
          overwrite: true
          file_glob: true
          body: ""

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
#      - name: Get version
#        id: get_version
#        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: ncipollo/release-action@v1
        with:
          tag_name: ${{ github.ref_name }}
          generateReleaseNotes: true
