name: publish release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps/get_version.outputs.VERSION }}
          generateReleaseNotes: true
